### ISSUE TITLE
chardet throws error

### ISSUE THREAD

**Issue by uahim** [cyberang3l/subtitle-cleaner#1]
> $ python subtitle-cleaner.py -i input.srt -o output.srt
> Traceback (most recent call last):
>   File "subtitle-cleaner.py", line 89, in <module>
>     guess = chardet.detect(content)
>   File "C:\gnu\Python36\lib\site-packages\chardet\__init__.py", line 25, in detect
>     raise ValueError('Expected a bytes object, not a unicode object')
> ValueError: Expected a bytes object, not a unicode object

any idea what went wrong?

**Comment by cyberang3l** [comment]
You are using python 3.
I have tested the script and is working nicely with python 2.

**Comment by cyberang3l** [comment]
I think I fixed the problem and now it is working on python 3 as well. Pull the latest version and let me know if it's working for you as well.

**Comment by uahim** [comment]
@cyberang3l works like a charm, thank you.
